//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPrint.ServiceReferenc2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Printer", Namespace="http://schemas.datacontract.org/2004/07/WcfPrintService")]
    [System.SerializableAttribute()]
    public partial class Printer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Pc_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prn_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pc_name {
            get {
                return this.Pc_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.Pc_nameField, value) != true)) {
                    this.Pc_nameField = value;
                    this.RaisePropertyChanged("Pc_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prn_name {
            get {
                return this.Prn_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.Prn_nameField, value) != true)) {
                    this.Prn_nameField = value;
                    this.RaisePropertyChanged("Prn_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pqueue", Namespace="http://schemas.datacontract.org/2004/07/WcfPrintService")]
    [System.SerializableAttribute()]
    public partial class Pqueue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FileStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PapersPrintingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PcNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PqueueDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrintPagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PrintedConfirmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrinterIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FileStatus {
            get {
                return this.FileStatusField;
            }
            set {
                if ((this.FileStatusField.Equals(value) != true)) {
                    this.FileStatusField = value;
                    this.RaisePropertyChanged("FileStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filename {
            get {
                return this.FilenameField;
            }
            set {
                if ((object.ReferenceEquals(this.FilenameField, value) != true)) {
                    this.FilenameField = value;
                    this.RaisePropertyChanged("Filename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageFrom {
            get {
                return this.PageFromField;
            }
            set {
                if ((this.PageFromField.Equals(value) != true)) {
                    this.PageFromField = value;
                    this.RaisePropertyChanged("PageFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageTo {
            get {
                return this.PageToField;
            }
            set {
                if ((this.PageToField.Equals(value) != true)) {
                    this.PageToField = value;
                    this.RaisePropertyChanged("PageTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PapersPrinting {
            get {
                return this.PapersPrintingField;
            }
            set {
                if ((this.PapersPrintingField.Equals(value) != true)) {
                    this.PapersPrintingField = value;
                    this.RaisePropertyChanged("PapersPrinting");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PcName {
            get {
                return this.PcNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PcNameField, value) != true)) {
                    this.PcNameField = value;
                    this.RaisePropertyChanged("PcName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PqueueDateTime {
            get {
                return this.PqueueDateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PqueueDateTimeField, value) != true)) {
                    this.PqueueDateTimeField = value;
                    this.RaisePropertyChanged("PqueueDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrintPages {
            get {
                return this.PrintPagesField;
            }
            set {
                if ((object.ReferenceEquals(this.PrintPagesField, value) != true)) {
                    this.PrintPagesField = value;
                    this.RaisePropertyChanged("PrintPages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PrintedConfirm {
            get {
                return this.PrintedConfirmField;
            }
            set {
                if ((this.PrintedConfirmField.Equals(value) != true)) {
                    this.PrintedConfirmField = value;
                    this.RaisePropertyChanged("PrintedConfirm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrinterId {
            get {
                return this.PrinterIdField;
            }
            set {
                if ((this.PrinterIdField.Equals(value) != true)) {
                    this.PrinterIdField = value;
                    this.RaisePropertyChanged("PrinterId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenc2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InitializePrintersToDb", ReplyAction="http://tempuri.org/IService1/InitializePrintersToDbResponse")]
        void InitializePrintersToDb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InitializePrintersToDb", ReplyAction="http://tempuri.org/IService1/InitializePrintersToDbResponse")]
        System.Threading.Tasks.Task InitializePrintersToDbAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPrintersFromDb", ReplyAction="http://tempuri.org/IService1/GetPrintersFromDbResponse")]
        WebPrint.ServiceReferenc2.Printer[] GetPrintersFromDb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPrintersFromDb", ReplyAction="http://tempuri.org/IService1/GetPrintersFromDbResponse")]
        System.Threading.Tasks.Task<WebPrint.ServiceReferenc2.Printer[]> GetPrintersFromDbAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetQueueDataToDb", ReplyAction="http://tempuri.org/IService1/SetQueueDataToDbResponse")]
        void SetQueueDataToDb(WebPrint.ServiceReferenc2.Pqueue pqueue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetQueueDataToDb", ReplyAction="http://tempuri.org/IService1/SetQueueDataToDbResponse")]
        System.Threading.Tasks.Task SetQueueDataToDbAsync(WebPrint.ServiceReferenc2.Pqueue pqueue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPqueuesFromDb", ReplyAction="http://tempuri.org/IService1/GetPqueuesFromDbResponse")]
        WebPrint.ServiceReferenc2.Pqueue[] GetPqueuesFromDb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPqueuesFromDb", ReplyAction="http://tempuri.org/IService1/GetPqueuesFromDbResponse")]
        System.Threading.Tasks.Task<WebPrint.ServiceReferenc2.Pqueue[]> GetPqueuesFromDbAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebPrint.ServiceReferenc2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebPrint.ServiceReferenc2.IService1>, WebPrint.ServiceReferenc2.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InitializePrintersToDb() {
            base.Channel.InitializePrintersToDb();
        }
        
        public System.Threading.Tasks.Task InitializePrintersToDbAsync() {
            return base.Channel.InitializePrintersToDbAsync();
        }
        
        public WebPrint.ServiceReferenc2.Printer[] GetPrintersFromDb() {
            return base.Channel.GetPrintersFromDb();
        }
        
        public System.Threading.Tasks.Task<WebPrint.ServiceReferenc2.Printer[]> GetPrintersFromDbAsync() {
            return base.Channel.GetPrintersFromDbAsync();
        }
        
        public void SetQueueDataToDb(WebPrint.ServiceReferenc2.Pqueue pqueue) {
            base.Channel.SetQueueDataToDb(pqueue);
        }
        
        public System.Threading.Tasks.Task SetQueueDataToDbAsync(WebPrint.ServiceReferenc2.Pqueue pqueue) {
            return base.Channel.SetQueueDataToDbAsync(pqueue);
        }
        
        public WebPrint.ServiceReferenc2.Pqueue[] GetPqueuesFromDb() {
            return base.Channel.GetPqueuesFromDb();
        }
        
        public System.Threading.Tasks.Task<WebPrint.ServiceReferenc2.Pqueue[]> GetPqueuesFromDbAsync() {
            return base.Channel.GetPqueuesFromDbAsync();
        }
    }
}
